media:
  - name: images
    label: "Media (obrazy)"
    input: "media/images"
    output: "/media/images"
    categories: [ image ]         # jpg, png, svg, webp itd.

  - name: docs
    label: "Dokumenty (/docs)"
    input: "docs"
    output: "/docs"
    categories: [ document ]      # pdf, doc, docx, xls, xlsx, txt, rtf, ppt, pptx
    # jeśli chcesz zawęzić typy wyświetlane w Media -> odkomentuj i dopasuj:
    # extensions: [ pdf, docx, xlsx, pptx, txt, rtf ]
