media:
  input: "media/images"
  output: "/media/images"

# Ustawienia globalne: bezpieczne łączenie zmian
settings:
  content:
    merge: true

content:
  # Kolekcja dokumentów Markdown w /docs
  - name: docs
    label: "Dokumenty (docs/*.md)"
    type: collection
    path: "docs"
    format: raw            # pliki .md bez frontmatteru
    subfolders: false
    fields:
      - name: body
        label: "Treść (Markdown)"
        type: rich-text    # edytor WYSIWYG zapisze Markdown do pliku
    view:
      fields: [ "path" ]   # prosta lista; możesz doprecyzować

  # (Opcjonalnie) pojedyncze pliki .md w katalogu głównym
  - name: root_md
    label: "Pliki Markdown w katalogu głównym (*.md)"
    type: collection
    path: "/"
    format: raw
    filename: "{primary}.md"
    exclude: [ "README.md" ]
    fields:
      - name: body
        label: "Treść (Markdown)"
        type: rich-text
    view:
      fields: [ "path" ]
